version: '3.7'
services:

    ping:
        build: ping

    soma:
        build: soma

    sub:
        build: sub

    mult-1:
        build: mult

    mult-2:
        build: mult

    mult-3:
        build: mult

    nginx:
        container_name: nginx
        build: nginx
        ports:
            - 8080:80
        depends_on:
           - ping
           - soma
           - sub
           - mult-1
           - mult-2
           - mult-3