events {}

http {
    # Grupo de servidores para multiplicação (Load Balancer)
    upstream mult_servers {
        server microservice-calc-mult-1:5000 weight=3; 
        server microservice-calc-mult-2:5000 weight=1; 
        server microservice-calc-mult-3:5000 backup;   
    }

    server {
        listen 80;
        server_name app.com;

        # Rota para o novo microserviço
        location /mult {
            proxy_pass http://mult_servers;
        }

        location /ping {
            proxy_pass http://microservice-calc_ping_1:5000;
        }

        location /soma {
            proxy_pass http://microservice-calc_soma_1:5000;
        }

        location /sub {
            proxy_pass http://microservice-calc_sub_1:5000;
        }
    }
}